{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:01:47 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"1\" QueryFailedError: неверный синтаксис для типа uuid: \"1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:04:37 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"1\" QueryFailedError: неверный синтаксис для типа uuid: \"1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:05:31 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"1\" QueryFailedError: неверный синтаксис для типа uuid: \"1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:06:25 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"1\" QueryFailedError: неверный синтаксис для типа uuid: \"1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:09:30 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"1\" QueryFailedError: неверный синтаксис для типа uuid: \"1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:14:15 GMT+0300 (Москва, стандартное время) TypeError: Class constructor User cannot be invoked without 'new' TypeError: Class constructor User cannot be invoked without 'new'\n    at SelectQueryBuilder.QueryBuilder.getWhereCondition (E:\\nodeCurs\\nodejs2021Q4-service\\src\\query-builder\\QueryBuilder.ts:1198:20)\n    at SelectQueryBuilder.where (E:\\nodeCurs\\nodejs2021Q4-service\\src\\query-builder\\SelectQueryBuilder.ts:720:32)\n    at getAllMemory (E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.memory.repository.ts:17:6)\n    at getAllServis (E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.service.ts:14:40)\n    at E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.router.ts:19:35\n    at Layer.handle [as handle_request] (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at Layer.handle [as handle_request] (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\router\\index.js:281:22"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:14:40 GMT+0300 (Москва, стандартное время) QueryFailedError: аргумент конструкции WHERE должен иметь тип boolean, а не name QueryFailedError: аргумент конструкции WHERE должен иметь тип boolean, а не name\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:15:26 GMT+0300 (Москва, стандартное время) TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'EntityMetadata'\n    |     property 'ownColumns' -> object with constructor 'Array'\n    |     index 0 -> object with constructor 'ColumnMetadata'\n    --- property 'entityMetadata' closes the circle TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'EntityMetadata'\n    |     property 'ownColumns' -> object with constructor 'Array'\n    |     index 0 -> object with constructor 'ColumnMetadata'\n    --- property 'entityMetadata' closes the circle\n    at JSON.stringify (<anonymous>)\n    at getAllMemory (E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.memory.repository.ts:18:30)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.router.ts:19:17"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:33:05 GMT+0300 (Москва, стандартное время) QueryFailedError: неоднозначная ссылка на столбец \"id\" QueryFailedError: неоднозначная ссылка на столбец \"id\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 18:34:48 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/243b3c0f-aa9e-4f12-8ed5-8998d6d72644\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 18:35:21 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/ce95f3cb-e091-4b76-9a9d-20da025f507a\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 18:42:07 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/ce95f3cb-e091-4b76-9a9d-20da025f507a\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 18:42:26 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/ce95f3cb-e091-4b76-9a9d-20da025f507a\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 18:57:09 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/67705fef-6e36-4074-a5a6-937bb7386a25\n Query Parameters: {} Body: {}"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 18:57:54 GMT+0300 (Москва, стандартное время) TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'EntityMetadata'\n    |     property 'ownColumns' -> object with constructor 'Array'\n    |     index 0 -> object with constructor 'ColumnMetadata'\n    --- property 'entityMetadata' closes the circle TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'EntityMetadata'\n    |     property 'ownColumns' -> object with constructor 'Array'\n    |     index 0 -> object with constructor 'ColumnMetadata'\n    --- property 'entityMetadata' closes the circle\n    at JSON.stringify (<anonymous>)\n    at stringify (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\response.js:1123:12)\n    at ServerResponse.json (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\express\\lib\\response.js:260:14)\n    at E:\\nodeCurs\\nodejs2021Q4-service\\src\\resources\\users\\user.router.ts:52:23\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 19:12:35 GMT+0300 (Москва, стандартное время) EntityNotFoundError: Could not find any entity of type \"User\" matching: [object Object] EntityNotFoundError: Could not find any entity of type \"User\" matching: [object Object]\n    at EntityNotFoundError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new EntityNotFoundError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\EntityNotFoundError.ts:10:9)\n    at SelectQueryBuilder.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\query-builder\\SelectQueryBuilder.ts:1131:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.next (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at fulfilled (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:114:62)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 19:17:25 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/67705fef-6e36-4074-a5a6-937bb7386a24\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 19:17:49 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/67705fef-6e36-4074-a5a6-937bb7386a24\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 19:18:35 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/67705fef-6e36-4074-a5a6-937bb7386a24\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 19:23:42 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/74d4bfcd-7178-428d-b785-9d9a4943f535\n Query Parameters: {} Body: {}"}
{"level":"error","message":"   Unhandled rejection detected: Fri Jan 14 2022 19:27:31 GMT+0300 (Москва, стандартное время) QueryFailedError: столбец \"users.id\" должен фигурировать в предложении GROUP BY или использоваться в агрегатной функции QueryFailedError: столбец \"users.id\" должен фигурировать в предложении GROUP BY или использоваться в агрегатной функции\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 19:33:34 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /users/74d4bfcd-7178-428d-b785-9d9a4943f535\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/80bac2c4-4119-4a81-8c67-135d192ff85a\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c7ca969f-c191-466d-a862-d6d8d847d7c5/tasks/0edc60fa-10ce-4a0e-8577-9c7dd587e592\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c7ca969f-c191-466d-a862-d6d8d847d7c5/tasks/90136d2f-c1c8-462e-8b28-0b2d8cb25c8e\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c7ca969f-c191-466d-a862-d6d8d847d7c5/tasks/52d397d4-dd8a-47c6-828a-5840a74e0718\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c7ca969f-c191-466d-a862-d6d8d847d7c5/tasks/86800ee7-2bbd-4d80-83b0-8d68781bfbfb\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c7ca969f-c191-466d-a862-d6d8d847d7c5/tasks/12d6660b-c508-4634-a498-0326a716841f\n Query Parameters: {} Body: {}"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 21:20:00 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /boards/c5acfc45-9fd8-4d8a-b8fd-ef1ae9dfca69/tasks/06851955-34cf-4ffb-8c3f-37545e0e2f44\n Query Parameters: {} Body: {}"}
{"level":"error","message":"   StatusCode: SyntaxError: Unexpected token / in JSON at position 33"}
{"level":"error","message":"   StatusCode: SyntaxError: Unexpected token / in JSON at position 33"}
{"level":"error","message":"   StatusCode: SyntaxError: Unexpected token / in JSON at position 33"}
{"level":"error","message":"   StatusCode: SyntaxError: Unexpected token / in JSON at position 33"}
{"level":"warn","message":"     WARN LEVEL => Fri Jan 14 2022 22:59:15 GMT+0300 (Москва, стандартное время)\n StatusCode: 404;\n URL: /board\n Query Parameters: {} Body: {\"title\":\"qqqqq123\",\"columns\":[{\"title\":\"wwwww456\",\"order\":\"67\"},{\"title\":\"eeeeee5768i\",\"order\":\"55\"}]}"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:31:45 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа boolean: \"5036979d-8553-4d96-bc4f-be62e08e8e8e\" QueryFailedError: неверный синтаксис для типа boolean: \"5036979d-8553-4d96-bc4f-be62e08e8e8e\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:33:38 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа boolean: \"5036979d-8553-4d96-bc4f-be62e08e8e8e\" QueryFailedError: неверный синтаксис для типа boolean: \"5036979d-8553-4d96-bc4f-be62e08e8e8e\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:34:10 GMT+0300 (Москва, стандартное время) QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:35:24 GMT+0300 (Москва, стандартное время) QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:41:26 GMT+0300 (Москва, стандартное время) QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 12:43:58 GMT+0300 (Москва, стандартное время) QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL QueryFailedError: значение NULL в столбце \"title\" отношения \"task\" нарушает ограничение NOT NULL\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 13:03:51 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа integer: \"order1\" QueryFailedError: неверный синтаксис для типа integer: \"order1\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 13:04:52 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"userId\" QueryFailedError: неверный синтаксис для типа uuid: \"userId\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 13:05:46 GMT+0300 (Москва, стандартное время) QueryFailedError: неверный синтаксис для типа uuid: \"5\" QueryFailedError: неверный синтаксис для типа uuid: \"5\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 14:07:03 GMT+0300 (Москва, стандартное время) QueryFailedError: таблица \"users\" отсутствует в предложении FROM QueryFailedError: таблица \"users\" отсутствует в предложении FROM\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
{"level":"error","message":"   Unhandled rejection detected: Sat Jan 15 2022 14:07:36 GMT+0300 (Москва, стандартное время) QueryFailedError: в элементе предложения FROM неверная ссылка на таблицу \"task\" QueryFailedError: в элементе предложения FROM неверная ссылка на таблицу \"task\"\n    at QueryFailedError.TypeORMError [as constructor] (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\TypeORMError.ts:7:9)\n    at new QueryFailedError (E:\\nodeCurs\\nodejs2021Q4-service\\src\\error\\QueryFailedError.ts:9:9)\n    at PostgresQueryRunner.<anonymous> (E:\\nodeCurs\\nodejs2021Q4-service\\src\\driver\\postgres\\PostgresQueryRunner.ts:247:19)\n    at step (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:143:27)\n    at Object.throw (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:124:57)\n    at rejected (E:\\nodeCurs\\nodejs2021Q4-service\\node_modules\\tslib\\tslib.js:115:69)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}
